<h1>Essentials of NumPy</h1>

In [1]:
import numpy as np

In [2]:
#Creating a 1-D array
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [3]:
#Creating a 2-D Array
a = np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#Getting dimension of an array
a.ndim

2

In [5]:
# Getting number of rows and columns
a.shape

(2, 3)

In [6]:
#Creating numpy array using linspace
a = np.linspace(0, 1, 6)

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [7]:
# Creating a numpy array using arange
a = np.arange(1, 10, 2)

a

array([1, 3, 5, 7, 9])

In [8]:
# Creating numpy array with all values as one
a = np.ones((2, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Creating numpy array with all values as zero
a = np.zeros((2, 2))

a

array([[0., 0.],
       [0., 0.]])

In [10]:
# Creating identity matrix
a = np.eye(3)

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a = np.eye(2, 3)

a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [12]:
# Creating a diognal matrix
a = np.diag([1, 2, 3, 4, 5])

a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [13]:
# Create a random array
a = np.random.rand(4)

a

array([0.17412518, 0.19292698, 0.97057114, 0.9036759 ])

In [14]:
# Create a random array
a = np.random.rand(4, 3)

a

array([[0.10052744, 0.83166203, 0.36948499],
       [0.24384249, 0.6603846 , 0.24135782],
       [0.0703986 , 0.34707742, 0.21372777],
       [0.76753362, 0.42108449, 0.22774047]])

In [15]:
#Returns datatype of values of the array
a.dtype

dtype('float64')

In [16]:
#Typecasting numpy array
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(10, dtype='float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Slicing in numpy array
b = a[::2]

b

array([0, 2, 4, 6, 8])

In [20]:
np.shares_memory(a, b)

True

In [21]:
b = a[::2].copy()

In [22]:
np.shares_memory(a, b)

False

In [23]:
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
mask = (a % 2 == 0)

a_masked = a[mask]

a_masked

array([0, 2, 4, 6, 8])

In [25]:
a = np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [26]:
a + 1

array([2, 3, 4, 5, 6])

In [27]:
a + 8

array([ 9, 10, 11, 12, 13])

In [28]:
a - 5

array([-4, -3, -2, -1,  0])

In [29]:
a * 2

array([ 2,  4,  6,  8, 10])

In [30]:
a ** 2

array([ 1,  4,  9, 16, 25])

In [31]:
a = np.diag([1, 2, 3, 4, 5])

a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
a * a

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [35]:
a * 5

array([[ 5,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 20,  0],
       [ 0,  0,  0,  0, 25]])

In [36]:
a.dot(a)

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

In [37]:
x = np.array([1, 1, 0, 0], dtype='bool')

x

array([ True,  True, False, False])

In [38]:
y = np.array([0, 1, 1, 0], dtype='bool')

y

array([False,  True,  True, False])

In [39]:
np.logical_and(x, y)

array([False,  True, False, False])

In [40]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [41]:
np.logical_not(x)

array([False, False,  True,  True])

In [42]:
np.logical_or(x, np.logical_not(y))

array([ True,  True, False,  True])

In [43]:
x = np.arange(1, 10, 1)

x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
y = np.array([6, 7, 3, 4, 9, 1, 20, 6, 8])

y

array([ 6,  7,  3,  4,  9,  1, 20,  6,  8])

In [45]:
x == y

array([False, False,  True,  True, False, False, False, False, False])

In [46]:
y

array([ 6,  7,  3,  4,  9,  1, 20,  6,  8])

In [47]:
np.sum(y)

64

In [48]:
np.min(y)

1

In [49]:
np.max(y)

20

In [50]:
np.argmin(y)

5

In [51]:
np.argmax(y)

6

In [52]:
y

array([ 6,  7,  3,  4,  9,  1, 20,  6,  8])

In [53]:
y.mean()

7.111111111111111

In [54]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x.mean()

5.0

In [56]:
np.median(y)

6.0

In [58]:
np.median(x)

5.0

In [59]:
z = np.array([[1, 2, 3], [4, 5, 6]])

z

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.median(z, axis = 1)

array([2., 5.])

In [62]:
x.std()

2.581988897471611

In [63]:
x = np.array([1, 1, 0, 0], dtype='bool')

x

array([ True,  True, False, False])

In [64]:
y = np.array([0, 1, 1, 0], dtype='bool')

y

array([False,  True,  True, False])

In [65]:
np.any(x) # Logical or

True

In [66]:
np.all(x) # Logical and

False

In [7]:
import numpy as np

In [8]:
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [9]:
b = np.array([4, 5, 6])

b

array([4, 5, 6])

In [10]:
b = b[: , np.newaxis]

b

array([[4],
       [5],
       [6]])

In [11]:
a + b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [12]:
a - b

array([[-3, -2, -1],
       [-4, -3, -2],
       [-5, -4, -3]])