<h1>Essentials of NumPy</h1>

In [2]:
import numpy as np

In [3]:
#Creating a 1-D array
a = np.array([1, 2, 3])

a

array([1, 2, 3])

In [5]:
#Creating a 2-D Array
a = np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#Getting dimension of an array
a.ndim

2

In [7]:
# Getting number of rows and columns
a.shape

(2, 3)

In [8]:
#Creating numpy array using linspace
a = np.linspace(0, 1, 6)

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [9]:
# Creating a numpy array using arange
a = np.arange(1, 10, 2)

a

array([1, 3, 5, 7, 9])

In [10]:
# Creating numpy array with all values as one
a = np.ones((2, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# Creating numpy array with all values as zero
a = np.zeros((2, 2))

a

array([[0., 0.],
       [0., 0.]])

In [13]:
# Creating identity matrix
a = np.eye(3)

a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a = np.eye(2, 3)

a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [17]:
# Creating a diognal matrix
a = np.diag([1, 2, 3, 4, 5])

a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [4]:
# Create a random array
a = np.random.rand(4)

a

array([0.55952569, 0.42397781, 0.37457749, 0.8518351 ])

In [3]:
# Create a random array
a = np.random.rand(4, 3)

a

array([[0.49350345, 0.23120818, 0.93480328],
       [0.61447893, 0.39602644, 0.85930172],
       [0.28701263, 0.70628406, 0.94642894],
       [0.38102713, 0.82730833, 0.04676637]])

In [19]:
#Returns datatype of values of the array
a.dtype

dtype('float64')

In [20]:
#Typecasting numpy array
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a = np.arange(10, dtype='float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Slicing in numpy array
b = a[::2]

b

array([0, 2, 4, 6, 8])

In [26]:
np.shares_memory(a, b)

True

In [27]:
b = a[::2].copy()

In [28]:
np.shares_memory(a, b)

False

In [29]:
a = np.arange(10, dtype='int64')

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
mask = (a % 2 == 0)

a_masked = a[mask]

a_masked

array([0, 2, 4, 6, 8])